sudo: required

language: python

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y jq

services:
  - docker

install:
  - VERSION=`curl https://api.github.com/repos/JustArchi/ArchiSteamFarm/releases/latest -s | jq .tag_name -r`

script:
  - docker build --build-arg GIT_TAG=${VERSION} -t yoannm/archisteamfarm:${VERSION} .

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker push yoannm/archisteamfarm:${VERSION}